[package]
name = "login"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
ractor = { workspace = true }
ractor_cluster = { workspace = true }
logging = {path = "../../misc/logging"}
tracing = "0.1.41"