[workspace]
members = [
    "resource/luban_lib",
    "resource/cfg",
    "resource/macros",
    "cmd/login",
    "protocol",
    "common",
    "servers",
]

[package]
name = "qs001-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
common = { path = "common" }
servers = { path = "servers" }
cfg = { path = "resource/cfg" }
luban_lib = { path = "resource/luban_lib" }


log = "0.4.26"
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
clap = { workspace = true }
anyhow = "1.0.97"
kameo = { workspace = true }
async-trait = { workspace = true }
bytes = "1.10.1"
[build-dependencies]


[workspace.dependencies]
arc-swap = "*"
tokio = { version = "*", features = ["full"] }
tracing = { version = "*", features = ["attributes"] }
tracing-subscriber = { version = "*", features = ["env-filter"] }
clap = { version = "*", features = ["derive"] }
anyhow = "*"
crossbeam-utils = "*"
bytes = "*"
prost = "*"
prost-build = "*"
serde = "*"
async-trait = "*"
kameo = { version = "0.15.0" }
thiserror = "*"
tokio-rustls = "*"