[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
ractor = { workspace = true }
bincode = "*"
prost = { workspace = true }
bytes="*"
serde = { version = "1.0.219", features = ["derive"] }
[build-dependencies]
prost-build = { workspace = true }
