#服务器集群的中心节点
center_in_address = "/ip4/192.168.1.12/udp/56666/quic-v1"
[config]
# bin|json
type = "bin"
[config.source_type.aws]
region = "us-east-1"
access_key_id = "AKIAIOSFODNN7EXAMPLE"
secret_access_key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
endpoint = "http://localhost:4566"
bucket = "qs001"
[log]
console = true
level = "info"
dir = "./logs"
max_file = 7

[[login]]
id = 1
in_address = "/ip4/192.168.1.12/udp/30000/quic-v1"
keydb = { host = "localhost", port = 6379, password = "", db = 0, pool_size = 16 }
[[gate]]
id = 1
in_address = "/ip4/192.168.1.12/udp/35000/quic-v1"
out_tcp_port = 5678
out_ws_port = 5679
out_udp_port = 5680

[[world]]
id = 1
in_address = "/ip4/192.168.1.12/udp/40000/quic-v1"

[[game]]
id = 1
in_address = "/ip4/192.168.1.12/udp/45000/quic-v1"
keydb = { host = "localhost", port = 6379, password = "", db = 0, pool_size = 16 }

