[[login]]
role = "Login"
id = 1
host = "0.0.0.0"
port = "30000"

[[gate]]
role = "Gate"
id = 1
host = "0.0.0.0"
port = "35000"

[[world]]
role = "World"
id = 1
host = "0.0.0.0"
port = "40000"

[[player]]
role = "Player"
id = 1
host = "0.0.0.0"
port = "45000"