[keydb]
host = "localhost"
port = 6379
password = ""
db = "0"
pool_size = 16

[aws]
region = "us-east-1"
access_key_id = "AKIAIOSFODNN7EXAMPLE"
secret_access_key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
endpoint = "http://localhost:4566"
bucket = "qs001"
[config]
# bin|json
type = "bin"