[database]
mysql_url = "mysql://user:password@localhost:3306"
redis_url = "redis://localhost:6379"
[mysql]
url="localhost:3306"

[aws]
region = "us-east-1"
access_key_id = "AKIAIOSFODNN7EXAMPLE"
secret_access_key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
endpoint = "http://localhost:4566"
bucket = "qs001"
[config]
# bin|json
type="bin"